### ISSUE TITLE
It is possible for players to not receive their cards

### ISSUE THREAD

**Issue by z64** [z64/discord-against-humanity#17]
Reported by @tikiki

"They could pick and got the confirmation, but not get the cards"

```
[ERROR : et-754 @ 2016-11-27 02:29:03.058] Exception: #<NoMethodError: undefined method `text' for nil:NilClass>
[ERROR : et-754 @ 2016-11-27 02:29:03.058] src/modules/database/player.rb:62:in `block in dm_unplayed'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/player.rb:61:in `each'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/player.rb:61:in `each_with_index'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/player.rb:61:in `dm_unplayed'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/game.rb:79:in `block in next_round!'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/game.rb:74:in `each'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/database/game.rb:74:in `next_round!'
[ERROR : et-754 @ 2016-11-27 02:29:03.059] src/modules/events/play.rb:132:in `block in <module:Play>'
```

**Comment by z64** [comment]
If this happens, please do not delete the game (`dah.end` or delete the channel) and send me a DM so that I can inspect the database for more info as to a root cause for this issue. (I'm `Lune#2639`)
